//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3655
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flavor.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flavor.Forms.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First collector.
        /// </summary>
        internal static string CollectorsForm_Col1Title {
            get {
                return ResourceManager.GetString("CollectorsForm_Col1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second collector.
        /// </summary>
        internal static string CollectorsForm_Col2Title {
            get {
                return ResourceManager.GetString("CollectorsForm_Col2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff - .
        /// </summary>
        internal static string CollectorsForm_DiffTitle {
            get {
                return ResourceManager.GetString("CollectorsForm_DiffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (precise).
        /// </summary>
        internal static string CollectorsForm_PreciseTitle {
            get {
                return ResourceManager.GetString("CollectorsForm_PreciseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (scan).
        /// </summary>
        internal static string CollectorsForm_ScanTitle {
            get {
                return ResourceManager.GetString("CollectorsForm_ScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass, a.m.u..
        /// </summary>
        internal static string CollectorsForm_XAxisTitleMass {
            get {
                return ResourceManager.GetString("CollectorsForm_XAxisTitleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        internal static string CollectorsForm_XAxisTitleStep {
            get {
                return ResourceManager.GetString("CollectorsForm_XAxisTitleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage, V.
        /// </summary>
        internal static string CollectorsForm_XAxisTitleVoltage {
            get {
                return ResourceManager.GetString("CollectorsForm_XAxisTitleVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string GraphForm_YAxisTitle {
            get {
                return ResourceManager.GetString("GraphForm_YAxisTitle", resourceCulture);
            }
        }
    }
}
